### ISSUE TITLE
Finish the new .mute plugin

### ISSUE THREAD

**Issue by dmptrluke** [CloudBotIRC/CloudBotLegacy#13]

**Comment by neersighted** [comment]
Getting close, as per 
39147ef498246bfe1e250b111f31152a5e0afe54
0cbb886ae9fe4ca5c4b26b92462b1d7cc1d74b86
and
f1c30e2e0564f51ca892e0e4b59c9a94574c5b77

**Comment by dmptrluke** [comment]
Done: debe62f639 3012ecd3d8592416f5fad9f98f6ff27103bab737 a2ef632dcfce7127da92ea9ec3851bb82b801586

**Comment by neersighted** [comment]
- now known as ignore
