### ISSUE TITLE
Bot restarts when quitting

### ISSUE THREAD

**Issue by Vasher** [CloudBotIRC/CloudBotLegacy#161]
Everytime I told the bot to quit (.quit/.stop) I would get the exception below. This was caused by the bot being named "bot.py" instead of "cloudbot". Once I renamed the file the exception went away but a new problem was created in that the bot will now quit then reconnect.

```
Unhandled exception in thread started by <function run at 0xb70a64fc>
Traceback (most recent call last):
  File "core/main.py", line 63, in run
    out = func(input.inp, **kw)
  File "plugins/admin.py", line 113, in stop
    os.execl("./cloudbot", "cloudbot", "stop")
  File "/usr/local/lib/python2.7/os.py", line 312, in execl
    execv(file, args)
OSError: [Errno 2] No such file or directory
```

**Comment by urbels** [comment]
bot naming bot.py is correct. there was launcher called cloudbot.
