### ISSUE TITLE
Minecraft 1.7 ping

### ISSUE THREAD

**Issue by daboross** [CloudBotIRC/CloudBotLegacy#179]
It'd be nice of minecraft_ping.py was updated to use the minecraft 1.7 ping by default, falling back to 1.6 ping if the server doesn't respond.

1.7 ping specs are at http://wiki.vg/Server_List_Ping#1.7.

**Comment by BlaneyXYZ** [comment]
This may  help https://gist.github.com/barneygale/1209061

**Comment by daboross** [comment]
Ok. I've almost finished writing something for this

**Comment by daboross** [comment]
Pull request made https://github.com/ClouDev/CloudBot/pull/181
