### ISSUE TITLE
.calc not returning resuts

### ISSUE THREAD

**Issue by TheFiZi** [CloudBotIRC/CloudBotLegacy#184]
04:21:35 #gaming <FiZi> .calc 90 / 8350000000

Unhandled exception in thread started by <function run at 0x7f2dd20dc410>
Traceback (most recent call last):
  File "core/main.py", line 68, in run
    out = func(input.inp, **kw)
  File "plugins/wolframalpha.py", line 59, in wolframalpha
    return "{} - {}".format(ret, short_url)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 103: ordinal not in range(128)

**Comment by dmptrluke** [comment]
should be fixed!

**Comment by TheFiZi** [comment]
Confirmed resolved.
