### ISSUE TITLE
pip only

### ISSUE THREAD

**Issue by neersighted** [CloudBotIRC/CloudBotLegacy#19]
move all packages to pip, for ease of use across platforms, and for updated versions

**Comment by dmptrluke** [comment]
Explain how you plan to move the packages, how it will work, and how people will install the bot once the packages are in pip. Thanks

**Comment by neersighted** [comment]
Actually, its more of a change of README to use pip.
and we need to run the bot on pip versions of the packages.

**Comment by neersighted** [comment]
Done.  Future dependances will use PIP.  Also, wrapper will detect/install packages for the user
