### ISSUE TITLE
Make urlparse.py handle unicode chars in the title better

### ISSUE THREAD

**Issue by dmptrluke** [CloudBotIRC/CloudBotLegacy#21]
Right now it dies with:

UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 22: ordinal not in range(128)

**Comment by neersighted** [comment]
I patched irc.py for better unicode encoding.  Maybe this commit may help? a10370fdcd5ccfc8c9cf87ab4f679954df2317b8

**Comment by dmptrluke** [comment]
Fixed. Neer derped it up

**Comment by neersighted** [comment]
...
