### ISSUE TITLE
IPv6 and Update command for GeoIP

### ISSUE THREAD

**Issue by BlaneyXYZ** [CloudBotIRC/CloudBotLegacy#222]
These would be nice :)

**Comment by DhashS** [comment]
do we have to stick with the legacy DB, or is it OK to use a 3rd party API? I'll whip one up if it's the latter

**Comment by BlaneyXYZ** [comment]
Doesn't bother me

**Comment by DhashS** [comment]
all done. Take a look here [[edited]] do you have any complaints in functionality?
EDIT: new pull req link here, i had to move the libs into disabled stuff https://github.com/ClouDev/CloudBot/pull/280

**Comment by BlaneyXYZ** [comment]
After some testing it seems to break if info is missing (like ISP) can something be implemented if a field is missing? I really am grateful for your help

**Comment by DhashS** [comment]
```
 if is_valid_ip(inp):
    info = json_resp.items()
    for iter in range(1,len(info) + 1):
        final_return += "\x02" + json_resp.key()[iter] + "\x02" + ": " + json_resp.values()[iter]
    return final_return
```

This should work out fine
