### ISSUE TITLE
Integrate namegen code into namegen.py

### ISSUE THREAD

**Issue by dmptrluke** [CloudBotIRC/CloudBotLegacy#24]
Something for me to do another day - not really important (at all)

**Comment by neersighted** [comment]
Do you mean the code from wc_gen?

**Comment by dmptrluke** [comment]
No, not that. I was planning to simplify molecular.py and integrate it into the plugin itself. I might have a try at it tonight.

**Comment by dmptrluke** [comment]
Finished with the new name generator code.
