### ISSUE TITLE
Fix buggy .geoip code.

### ISSUE THREAD

**Issue by neersighted** [CloudBotIRC/CloudBotLegacy#28]
For some reason, geoip.py is always reporting Canada as a ip's location.  I'm planning to look at this later today, and see if it's a simple fix.  If it's not, and something is wrong with the database we are using, we need to brainstorm new services to use.  
#### Possible replacements:
- Maxmind

@lukeroge, any thoughts?

**Comment by neersighted** [comment]
Ah, it does not detect ip from nick. I got it to detect it from your own nick, gonna try to make it check all nicks later.

**Comment by dmptrluke** [comment]
Although the specific problem discussed in this issue isn't a problem, the geoip code is still pretty shit overall.
