### ISSUE TITLE
Add a scheduler

### ISSUE THREAD

**Issue by Grandmasg** [CloudBotIRC/CloudBotLegacy#293]
Is it possible to add a scheduler (something like: https://github.com/ccontavalli/python-scheduler)

For example:
- Birthdays 
- Special days
- rss feed news update every hour or every 5 minutes 
- etc.

And is it possible to message a specific channel?

**Comment by neersighted** [comment]
It's possible. Pulls are welcome. Join #cloudbot for help coding it. 

## 

neersighted 
neersighted.com | github.com/neersighted
