### ISSUE TITLE
Port translation commands to a new API (again)

### ISSUE THREAD

**Issue by dmptrluke** [CloudBotIRC/CloudBotLegacy#3]
Since Google has made its API a paid service, looks like we need a new API. Searching reveals MyGengo could be a decent alternative. It should be easy enough to transition,

**Comment by neersighted** [comment]
I've got a stand-alone program working. Now I just need to make it a plugin.

**Comment by neersighted** [comment]
Done!

**Comment by neersighted** [comment]
Nope, MyGengo will not work.  Moving to BING translation API next.

**Comment by dmptrluke** [comment]
Alright. I'll have a poke at this later perhaps

**Comment by neersighted** [comment]
I'm on it!

**Comment by dmptrluke** [comment]
I can't find anything, removed the mygengo translate plugin and pulled a version that uses the paid Google API. You can find both in ./disabled_plugins
