### ISSUE TITLE
Nicktracking/Auth/Perms

### ISSUE THREAD

**Issue by neersighted** [CloudBotIRC/CloudBotLegacy#30]
These features need to be developed order:
- Nicktracking should be able to keep track of users, even if nick, ident, or host change.
- Users should `/msg auth <user> <pass>` the bot, and logins should be regex capable (Like a IRCd O:Line)
- Perms should be a sieve, and applied like `@hook.somehook(auth.level(admin)`

**Comment by dmptrluke** [comment]
See #87
