### ISSUE TITLE
goo.gl shortener

### ISSUE THREAD

**Issue by R2D2Warrior** [CloudBotIRC/CloudBotLegacy#34]
Random request: URL Shortener using goo.gl. You can get the long url from the short one, and get analytics of the short url. :D Seems like it would  be cool to have.

~ R2D2

PS. All the fancy info that i don't fully understand is at https://developers.google.com/url-shortener/v1/getting_started

**Comment by neersighted** [comment]
Thanks for the link, will look into it!

**Comment by dmptrluke** [comment]
I don't really see how useful this will be, considering we already have a shorten plugin that uses bit.ly. They also provide analytics of every link.

**Comment by neersighted** [comment]
Did not mean to close that, whoops.

**Comment by dmptrluke** [comment]
We already have a suitable URL shortener - will not implement.
