### ISSUE TITLE
Perms/clean up/regex

### ISSUE THREAD

**Issue by Red-M** [CloudBotIRC/CloudBotLegacy#37]
Luke you should really clean up permission commands with one base command.
an authentication systems should be put in for everyone but the owner which should be put into the config. people can "login" to the bot by .auth login <username> <password> 
and logout by .auth logout
ignore should be done via a regex hostmask (eg <nick>!<ident>@<hostname> or _!test@_ to ignore anyone with the ident of test)

**Comment by dmptrluke** [comment]
See #87
