### ISSUE TITLE
op.py

### ISSUE THREAD

**Issue by Red-M** [CloudBotIRC/CloudBotLegacy#39]
topic doesnt work when spec'ing the chan to use it in.

if inp[0][0] == "#":
        out = "PRIVMSG %s :%s" % (inp[0], message)
    else:
        out = "TOPIC %s :%s" % (chan, message)

^ seems legit

**Comment by dmptrluke** [comment]
Will fix. That plugin is scheduled for a rewrite anyway

**Comment by dmptrluke** [comment]
.. soon, I swear >_>

**Comment by dmptrluke** [comment]
Plugin updated.
