### ISSUE TITLE
Color Striping in .mcping

### ISSUE THREAD

**Issue by BlaneyXYZ** [CloudBotIRC/CloudBotLegacy#40]
Section Signs appear when using .mcping on a server which has color codes in the MOTD 

Example: §6RoyalCraft Survival - Minecraft 1.4.5 - 1/26 players

Maybe replace them with IRC Colors?

**Comment by neersighted** [comment]
On 12/8/2012 10:42 PM, Nathan Blaney wrote:

> Section Signs appear when using .mcping on a server which has color
> codes in the MOTD
> 
> Example: §6RoyalCraft Survival - Minecraft 1.4.5 - 1/26 players
> 
> Maybe replace them with IRC Colors?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ClouDev/CloudBot/issues/40.

I agree, that needs a bit of work. I'll look into it over this weekend.

## 

  [PGP]: AF636755/Neer Sighted (neersighted) neersighted@myopera.com

**Comment by BlaneyXYZ** [comment]
Awesome Thanks :)

**Comment by dmptrluke** [comment]
I'll take a look too, if I can find the time :)

**Comment by md-5** [comment]
#51 actually translating the codes is a better option.
