### ISSUE TITLE
Fix support for legacy server ping format

### ISSUE THREAD

**Issue by dmptrluke** [CloudBotIRC/CloudBotLegacy#41]
When I updated the mcping plugin I broke support for the old server ping format, so the command fails on pre 1.4 servers.

**Comment by dmptrluke** [comment]
Fixed!

**Comment by neersighted** [comment]
On 12/9/2012 4:12 AM, Luke Rogers wrote:

> When I updated the mcping plugin I broke support for the old server ping
> format, so the command fails on pre 1.4 servers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ClouDev/CloudBot/issues/41.

Ouch. There is a new format? Please post it (I'm only familiar with the

## classic format, from pynetree).

  [PGP]: AF636755/Neer Sighted (neersighted) neersighted@myopera.com
