### ISSUE TITLE
seen plugin

### ISSUE THREAD

**Issue by urbels** [CloudBotIRC/CloudBotLegacy#42]
Please add to seen plugin this:
For now if bot are in like 4 channels and you check for someone - it says that this person are not talked to this channel while it talks in another. So it will be nice if it report from another channels too. If you get what i mean. :)

**Comment by neersighted** [comment]
On 12/11/2012 10:58 PM, Edža wrote:

> Please add to seen plugin this:
> For now if bot are in like 4 channels and you check for someone - it
> says that this person are not talked to this channel while it talks in
> another. So it will be nice if it report from another channels too. If
> you get what i mean. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ClouDev/CloudBot/issues/42.

Not a bad idea. @Lukeroge, what do you think?

## 

  [PGP]: AF636755/Neer Sighted (neersighted) neersighted@myopera.com

**Comment by dmptrluke** [comment]
This is by design - we don't want the bot leaking private messages from other channels.

**Comment by urbels** [comment]
The idea behind this is not leaking messages. Bot should detect joins/parts.

**Comment by antdking** [comment]
just chucking it out there, but why not just say when they were last seen, and not what they said, if they were seen on a different channel. It makes it so it's more up to date, and doesn't compromise private messages

**Comment by urbels** [comment]
yep
