### ISSUE TITLE
Censor - Empty

### ISSUE THREAD

**Issue by md-5** [CloudBotIRC/CloudBotLegacy#44]
Having [] or [""] as your censored strings value censors evrything.

**Comment by neersighted** [comment]
On 01/09/2013 10:23 PM, md-5 wrote:

> Having [] or [""] as your censored strings value censors evrything.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ClouDev/CloudBot/issues/44.

All I have to say is lol... @Luke, wanna fix it for me?

## 

  Neer Sighted (neersighted) neersighted@myopera.com

  [PGP]: AF636755 | neersighted@myopera.com
  [Website]: http://neersighted.com | http://neersighted.github.com

**Comment by dmptrluke** [comment]
Seems to be fixed in 52a1e58db1f66c2429c82af461f4d56cf59bf202 :)
