### ISSUE TITLE
my bot died 3 times in ~7 days with this

### ISSUE THREAD

**Issue by urbels** [CloudBotIRC/CloudBotLegacy#49]
Unhandled exception in thread started by <bound method crlf_tcp.run of <__main__.crlf_tcp object at 0xcf3ad0>>
Traceback (most recent call last):
  File "core/irc.py", line 45, in run
    self.socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out

**Comment by neersighted** [comment]
That's a socket timeout exception.   It means that the connection to the
server was lost.

On Tue, Feb 26, 2013, at 02:53 AM, Edža wrote:

> Unhandled exception in thread started by <bound method crlf_tcp.run of
> <__main__.crlf_tcp object at 0xcf3ad0>>
> Traceback (most recent call last):
>   File "core/irc.py", line 45, in run
>     self.socket.connect((self.host, self.port))
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
> socket.timeout: timed out
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClouDev/CloudBot/issues/49

## 

Neer Sighted, Hacker 
http://neersighted.com | neersighted@myopera.com {01DC2056}

**Comment by urbels** [comment]
Any possibility to raise ping time for me?

**Comment by thenoodle68** [comment]
Not really no.
