### ISSUE TITLE
Syntax Errors in Core files

### ISSUE THREAD

**Issue by neersighted** [CloudBotIRC/CloudBotLegacy#5]
```
master!neerbot> python bot.py
Loading plugins
Traceback (most recent call last):
  File "core/reload.py", line 51, in reload
    eval(compile(open(filename, 'U').read(), filename, 'exec'),
  File "core/irc.py", line 76
     except (self.get_timeout_exception_type(), socket.error) as e:
                                                               ^
 SyntaxError: invalid syntax
master!neerbot>
```

Seems something is derped.  I've cherry-picked like mad, and also have completely wiped the bot, but it just won't start...

**Comment by dmptrluke** [comment]
Thats odd. The core should be all but identical to Skybot, which doesn't have such an error. I see you went to TheNoodle in IRC, so I'll leave this to him. Would you be able to post your Python version here?

**Comment by neersighted** [comment]
lolderp, _somehow_ python is python 2.5. Time to run python2.7 as my command from now on.
