### ISSUE TITLE
Easy new plugin idea - show length of message

### ISSUE THREAD

**Issue by nasonfish** [CloudBotIRC/CloudBotLegacy#56]
I can't send the PR right now, but something like this:

```
@hook.command
def length(inp):
    return "The length of that message is %s characters" % len(inp)
```

Pretty straightforward, but it could be pretty useful just to have there, instead of having to do `;py print len("lalalalala");` or something

**Comment by nasonfish** [comment]
Huh, I have no idea why I sent this. This is kinda lame. Sorry.

**Comment by dmptrluke** [comment]
Na. It's easy, and it can be useful in some cases :)

**Comment by nasonfish** [comment]
Oh, I didn't even notice you already implemented it. Sorry for not doing it myself, and thanks. :-)
