### ISSUE TITLE
mccraft and mcitem are outdated`

### ISSUE THREAD

**Issue by dmptrluke** [CloudBotIRC/CloudBotLegacy#58]
New items and recipes need to be added to these commands.

**Comment by BlaneyXYZ** [comment]
Here is itemids.txt http://pastebin.com/M2D6bpY4

**Comment by dmptrluke** [comment]
mcitem is updated, mccraft is yet to be updated

**Comment by daboross** [comment]
Isn't this fixed now?

**Comment by BlaneyXYZ** [comment]
For now yeah
