### ISSUE TITLE
Cloudbot can't read messages that comes from ingame with craftirc!

### ISSUE THREAD

**Issue by tryy3** [CloudBotIRC/CloudBotLegacy#93]
HI, I am wondering if you could make it so cloudbot can read messages that comes from craftirc, example
CraftircBot: <admin> <tryy3>: .bukkit
it won't read that maybe something like *.bukkit  so it reads anything that is before that, because usually people got different setups on their perms/craftirc, or possibly make it so you need to add the bot to some sort of safe bot or similar!
Anyway I been wanting this long time, and I forgot I could make an issue :)

**Comment by dmptrluke** [comment]
I'll investigate this, but it will probably be a config option. There are a lot of different formats people use for it

**Comment by tryy3** [comment]
Okej thanks :)
You could make it so, you need to type in the format in the config file? :)
